name: SnowSQL
on:
  workflow_dispatch:


jobs:
  snowsql:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Descargar SnowSQL
        run: curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.4/linux_x86_64/snowsql-1.4.3-linux_x86_64.bash
      - name: Instalar SnowSQL
        run: SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.4.3-linux_x86_64.bash
      - name: Revisar versi√≥n
        run: ~/bin/snowsql -v
      - name: Ejecutar Query SQL
        run: ~/bin/snowsql -f ./scripts/query.sql
        env:
          SNOWSQL_USER: ${{ secrets.SNOWSQL_USER  }}
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT  }}
          SNOWSQL_PWD: ${{ secrets.SNOWSQL_PWD  }}